apiVersion: v1
kind: Service
metadata:
  name: salu-portfolio-svc
  namespace: portfolio
spec:
  selector:
    app: salu-portfolio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
